version: "3"

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/daniel-koett/08-week/motion-full-stack-testing:latest
    ports:
      - 8001:8000
    volumes:
      - ./backend:/backend
    env_file:
      - ./env/dev.env
    command: "sh /scripts/dev.sh"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    env_file:
      - ./env/dev.env
    ports:
      - 5555:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db: