name: motion-project-backend
dependencies:
  - python
  - pip
  - psycopg2
  - pip:
      - django==4.0.5
      - djangorestframework==3.13.1
      - djangorestframework-simplejwt==5.2.0
      - drf-yasg==1.20.0
      - flake8
      - gunicorn
      - pillow
      - django-cors-headers

