# Generated by Django 4.0.5 on 2022-06-30 15:39

from django.conf import settings
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_friend_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=users.models.code_generator, max_length=5)),
                ('code_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='receiver',
            field=models.ManyToManyField(blank=True, null=True, related_name='receiver_fr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friend_request',
            name='sender',
            field=models.ManyToManyField(blank=True, null=True, related_name='sent_fr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='follwers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='firends_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(related_name='things_user_likes', to='users.interest'),
        ),
    ]
