# Generated by Django 4.0.5 on 2022-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resetpassword_alter_friend_request_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(blank=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='things_user_likes', to='users.interest'),
        ),
    ]
