# Generated by Django 4.0.5 on 2022-07-01 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_alter_user_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_request',
            name='receiver',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_fr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='friend_request',
            name='sender',
        ),
        migrations.AddField(
            model_name='friend_request',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_fr', to=settings.AUTH_USER_MODEL),
        ),
    ]
