# Generated by Django 4.0.5 on 2022-06-29 07:35

import Registration_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_profile',
            name='code',
            field=models.CharField(blank=True, default=Registration_profile.models.code_generator, max_length=5, null=True),
        ),
    ]
