# Generated by Django 4.0.5 on 2022-06-29 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Registration_profile', '0002_alter_registration_profile_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registration_profile',
            new_name='RegistrationProfile',
        ),
    ]
